import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowUpRight, ChevronRight, Crown, Flame, LockKeyhole, MessageSquare, Radio, Target, Trophy, Users, Zap } from 'lucide-react';
import { money, signedMoney } from '../economy/money';
import { AUDIENCE } from '../config/audience';
import type { AudienceBet, AudienceSnapshot, LeaderboardEntry, LeaderboardMetric, TimeFilter } from '../simulation/types';
import type { GameEngine } from '../game/engine';
import type { Snapshot } from '../types';

const integer = (value: number) => value.toLocaleString('en-US');
export function SpectatorAvatar({ name, color, you = false }: { name: string; color: string; you?: boolean }) {
  return <span className={`spectator-avatar ${you ? 'you' : ''}`} style={{ color, borderColor: `${color}44`, background: `${color}12` }} aria-hidden="true">{you ? 'Y' : name.slice(0, 2).toUpperCase()}</span>;
}
export function CrowdHUD({ audience }: { audience: AudienceSnapshot }) {
  return <div className="crowd-hud" aria-label="Simulated audience statistics"><div><span><span className="live-dot"/>LIVE AUDIENCE · SIMULATED</span><strong>{integer(audience.watchers)}<small>WATCHING</small></strong></div><div><span>BETS PLACED</span><strong>{integer(audience.betCount)}</strong></div><div><span>TOTAL BETS</span><strong>{money(audience.totalBets)}</strong></div></div>;
}
export function LiveBets({ audience }: { audience: AudienceSnapshot }) {
  return <section className="panel live-bets-panel"><div className="panel-heading"><h2><Target size={14}/>LIVE BETS<span className="small-tag">SIM</span></h2><span className={`bets-lock ${audience.locked ? 'locked' : ''}`}>{audience.locked ? <><LockKeyhole size={10}/>LOCKED</> : <><span className="live-dot"/>OPEN</>}</span></div><div className="live-bets-list"><AnimatePresence initial={false}>{audience.recentBets.slice(0, 4).map(bet => <motion.div key={bet.id} className={`live-bet ${bet.amount >= AUDIENCE.largeBet ? 'whale-bet' : ''} ${bet.isUser ? 'your-bet' : ''}`} initial={{ opacity: 0, y: -14, backgroundColor: bet.amount >= AUDIENCE.largeBet ? '#d6f65c33' : '#ffffff10' }} animate={{ opacity: 1, y: 0, backgroundColor: '#ffffff00' }} exit={{ opacity: 0 }} transition={{ duration: 0.28 }}><SpectatorAvatar name={bet.username} color={bet.avatar} you={bet.isUser}/><div><strong>{bet.username}{bet.amount >= AUDIENCE.largeBet && <Zap size={10}/>}</strong><small>{bet.type === 'winner' ? 'ROUND WINNER' : bet.type.toUpperCase()}</small></div><span><b>{money(bet.amount)}</b><small>→ {bet.fighterName}</small></span></motion.div>)}</AnimatePresence>{!audience.recentBets.length && <div className="empty-state"><Target size={18}/><span>The crowd is making its calls...</span></div>}</div><div className="live-bets-footer">{audience.locked ? 'The book is closed. Every bet is locked.' : 'Fictional spectators. Real suspense.'}</div></section>;
}
export function BroadcastFeed({ state }: { state: Snapshot }) {
  const [tab, setTab] = useState<'chat' | 'battle' | 'market'>('chat');
  return <section className="panel broadcast-panel"><div className="panel-heading"><h2><MessageSquare size={14}/>THE UNDERGROUND<span className="live-dot"/></h2><span className="small-tag">SIMULATED CHAT</span></div><div className="broadcast-tabs" role="tablist" aria-label="Broadcast feed">{(['chat', 'battle', 'market'] as const).map(t => <button key={t} role="tab" aria-selected={tab === t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)}>{t === 'chat' ? <MessageSquare size={12}/> : t === 'battle' ? <Radio size={12}/> : <Zap size={12}/>} {t === 'chat' ? 'Live chat' : t === 'battle' ? 'Battle events' : 'Market tape'}</button>)}</div><div className="broadcast-lines"><AnimatePresence initial={false}>
    {tab === 'chat' && state.audience.reactions.slice(0, 6).map(message => <motion.div className={`chat-line ${message.kind === 'upset' ? 'upset' : ''}`} key={`chat-${message.id}`} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.2 }}><SpectatorAvatar name={message.username} color={message.avatar}/><p><strong style={{ color: message.avatar }}>{message.username}</strong><span>{message.text}</span></p><time>{new Date(message.time).toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit' })}</time></motion.div>)}
    {tab === 'battle' && state.feed.slice(0, 6).map(item => <motion.div className="chat-line battle-line" key={`battle-${item.id}`} initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Radio size={13} style={{ color: item.color }}/><p><strong>{item.text}</strong><span>{item.detail}</span></p></motion.div>)}
    {tab === 'market' && state.audience.market.map(quote => <div className="chat-line" key={quote.symbol}><span className="crypto-symbol" style={{ color: quote.color }}>{quote.symbol[0]}</span><p><strong>{quote.symbol} · {quote.name}</strong><span>{quote.change >= 0 ? 'Buying' : 'Selling'} pressure · {money(quote.volume)} simulated volume</span></p><span className={quote.change >= 0 ? 'positive' : 'negative'}>{quote.change >= 0 ? '+' : ''}{quote.change.toFixed(2)}%</span></div>)}
  </AnimatePresence></div><div className="broadcast-bottom"><span><Users size={11}/>{integer(state.audience.watchers)} fictional spectators</span><span>NO CASH VALUE</span></div></section>;
}
function WinnerRow({ bet, index = 0 }: { bet: AudienceBet; index?: number }) {
  return <motion.div className={`winner-row ${bet.isUser ? 'your-result' : ''}`} initial={{ opacity: 0, y: 9 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.09 }}><SpectatorAvatar name={bet.username} color={bet.avatar} you={bet.isUser}/><div><strong>{bet.username}{bet.isUser && <span>YOUR RESULT</span>}</strong><small>Bet {money(bet.amount)} · {bet.fighterName} · {bet.odds.toFixed(2)}×</small></div><span><b className={bet.payout >= bet.amount ? 'positive' : 'negative'}>{signedMoney(bet.payout - bet.amount)}</b><small>{money(bet.payout)} returned</small></span></motion.div>;
}
export function Winners({ audience, currentRound }: { audience: AudienceSnapshot; currentRound: number }) {
  const result = audience.results;
  return <section className="panel winners-panel"><div className="panel-heading"><h2><Trophy size={14}/>ROUND {String(result?.round ?? currentRound).padStart(3, '0')} WINNERS</h2><span className="small-tag">SIMULATED PAYOUTS</span></div>{result ? <><div className="winners-summary"><span><strong>{integer(result.winningBets)}</strong>WINNING BETS</span><span><strong className="lime">{money(result.paid)}</strong>TOTAL PAID</span><span className="winner-fighter">{result.winnerName}<small>{result.odds.toFixed(2)}× CLOSING ODDS</small></span></div><div className="winner-awards">{([['BIGGEST WIN', result.biggestWin, 'payout'], ['HIGHEST ODDS', result.highestOdds, 'odds'], ['BIGGEST PROFIT', result.biggestProfit, 'profit']] as const).map(([label, bet, field]) => <div key={label}><Crown size={12}/><small>{label}</small><strong>{bet?.username ?? '—'}</strong><span>{bet ? field === 'odds' ? `${bet.odds.toFixed(2)}×` : field === 'profit' ? signedMoney(bet.payout - bet.amount) : money(bet.payout) : 'No winning bets'}</span></div>)}</div><div className="winners-list">{result.user && <WinnerRow bet={result.user}/>} {result.winners.filter(b => !b.isUser).slice(0, 3).map((bet, i) => <WinnerRow key={bet.id} bet={bet} index={i + 1}/>)}</div>{!result.user && <p className="winner-spectator-note">You watched this one. Make a call in the next open window.</p>}</> : <div className="winners-waiting"><span className="winner-wait-icon"><Trophy size={33}/></span><span className="eyebrow">THE BRAGGING RIGHTS ARE STILL UP FOR GRABS</span><strong>WHO CALLED IT?</strong><p>Winners, biggest payouts, and your result<br/>appear here when the dust settles.</p><span><span className="live-dot"/>ROUND {String(currentRound).padStart(3, '0')} IN PROGRESS</span></div>}</section>;
}
export function CommunityPreview({ audience, open }: { audience: AudienceSnapshot; open: () => void }) {
  return <section className="panel community-preview"><div className="panel-heading"><h2><Crown size={14}/>GLOBAL LEADERBOARD<span className="small-tag">SIMULATED</span></h2><button className="text-button" onClick={open}>All rankings<ArrowUpRight size={13}/></button></div><div className="community-preview-rows">{audience.leaders.slice(0, 4).map(entry => <button key={entry.id} onClick={open}><span className="community-rank">#{entry.rank}</span><SpectatorAvatar name={entry.username} color={entry.avatar}/><span><strong>{entry.username}</strong><small>{integer(entry.wins)} wins · {entry.winRate.toFixed(1)}%</small></span><b className={entry.profit >= 0 ? 'positive' : 'negative'}>{signedMoney(entry.profit)}</b></button>)}</div><button className="your-rank-preview" onClick={open}><span>#{audience.userRank.rank}</span><strong>YOU <small>YOUR POSITION</small></strong><b className={audience.userRank.profit >= 0 ? 'positive' : 'negative'}>{signedMoney(audience.userRank.profit)}</b><ChevronRight size={14}/></button></section>;
}
const metrics: { key: LeaderboardMetric; label: string }[] = [{ key: 'profit', label: 'TOP PROFIT' }, { key: 'wins', label: 'MOST WINS' }, { key: 'winRate', label: 'BEST WIN RATE' }, { key: 'biggestWin', label: 'BIGGEST WIN' }, { key: 'streak', label: 'HOT STREAK' }, { key: 'losses', label: 'BIGGEST LOSSES' }];
export function GlobalLeaderboard({ engine, revision }: { engine: GameEngine; revision: number }) {
  const [metric, setMetric] = useState<LeaderboardMetric>('profit'), [time, setTime] = useState<TimeFilter>('all');
  const day = new Date().toISOString().slice(0, 10);
  const board = useMemo(() => engine.audience.leaderboard(metric, time), [engine, revision, metric, time, day]);
  return <><div className="leaderboard-intro"><p>A fictional crowd. A very competitive scoreboard.<br/><span>Rankings evolve with settled bets. Times use UTC.</span></p><div className="time-filters" role="group" aria-label="Leaderboard time period">{([['today', 'TODAY'], ['week', 'THIS WEEK'], ['all', 'ALL TIME']] as const).map(([key, label]) => <button key={key} className={time === key ? 'selected' : ''} aria-pressed={time === key} onClick={() => setTime(key)}>{label}</button>)}</div></div><div className="leaderboard-metrics" role="tablist" aria-label="Leaderboard category">{metrics.map(m => <button role="tab" aria-selected={metric === m.key} className={metric === m.key ? 'selected' : ''} key={m.key} onClick={() => setMetric(m.key)}>{m.label}</button>)}</div><div className="global-table-wrap"><table className="global-table"><thead><tr><th>RANK / SPECTATOR</th><th>BETS</th><th>W / L</th><th>WIN RATE</th><th>STREAK</th><th>BIGGEST WIN</th><th>PROFIT</th><th>FAVORITE</th>{metric === 'losses' && <th>LOST STAKES</th>}</tr></thead><tbody>{board.rows.map(row => <LeaderboardRow row={row} key={row.id} losses={metric === 'losses'}/>)}</tbody></table></div><div className="pinned-user-rank"><span className="small-tag">YOUR POSITION · {time === 'all' ? 'ALL TIME' : time === 'week' ? 'THIS WEEK' : 'TODAY'}</span><div><span>#{board.user.rank}</span><SpectatorAvatar name="YOU" color="#d6f65c" you/><strong>YOU</strong><small>{board.user.totalBets} bets · {board.user.wins} wins · {board.user.winRate.toFixed(1)}%</small><b className={board.user.profit >= 0 ? 'positive' : 'negative'}>{signedMoney(board.user.profit)}</b></div></div><p className="leaderboard-footnote">Showing 50 of {integer(AUDIENCE.population + 1)} participants. “Biggest win” is total returned; “biggest losses” ranks lost stakes. Spectators and their starting records are simulated.</p></>;
}
function LeaderboardRow({ row, losses }: { row: LeaderboardEntry; losses: boolean }) {
  return <tr className={row.isUser ? 'is-you' : ''}><td><span>#{row.rank}</span><SpectatorAvatar name={row.username} color={row.avatar} you={row.isUser}/><strong>{row.username}</strong></td><td>{row.totalBets}</td><td>{row.wins} / {row.losses}</td><td>{row.winRate.toFixed(1)}%</td><td>{row.streak > 1 && <Flame size={11}/>} {row.streak}</td><td>{money(row.biggestWin)}</td><td className={row.profit >= 0 ? 'positive' : 'negative'}>{signedMoney(row.profit)}</td><td>{row.favoriteFighter.toUpperCase()}</td>{losses && <td className="negative">{money(row.lostAmount)}</td>}</tr>;
}
