import { useEffect, useRef, useState } from 'react';
import { Activity, Check, ChevronRight, Eye, Heart, Shield, Skull, Sparkles, Swords, Target, Trophy, Volume2, X, Zap } from 'lucide-react';
import { motion } from 'motion/react';
import { Avatar, Coin, Sparkline } from './Primitives';
import { money, signedMoney } from '../economy/money';
import { MarketView } from './CryptoMarket';
import { GlobalLeaderboard } from './AudiencePanels';
import type { ModalName } from './Header';
import type { Fighter, Settings, Snapshot } from '../types';
import type { GameEngine } from '../game/engine';

export function Dialogs({ name, close, state, selected, engine, select }: { name: ModalName; close: () => void; state: Snapshot; selected: string; engine: GameEngine; select: (id: string) => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [historyTab, setHistoryTab] = useState('predictions');
  useEffect(() => {
    if (name) dialog.current?.showModal(); else dialog.current?.close();
    document.body.style.overflow = name ? 'hidden' : '';
    return () => { document.body.style.overflow = ''; };
  }, [name]);
  const fighter = state.fighters.find(f => f.id === selected)!;
  const titles: Record<NonNullable<ModalName>, string> = { fighters: 'MEET THE UNDERGROUND', market: 'THE RUMBLE EXCHANGE', history: 'YOUR CORNER OF THE ARENA', settings: 'TUNE YOUR EXPERIENCE', help: 'WELCOME TO THE RUMBLE', profile: 'FIGHTER DOSSIER', leaderboard: 'GLOBAL LEADERBOARD' };
  return <dialog ref={dialog} className={`app-dialog dialog-${name}`} onCancel={close} onClick={event => { if (event.target === event.currentTarget) close(); }} aria-labelledby="dialog-title"><div className="dialog-inner"><header className="dialog-header"><div><span className="eyebrow">PIXEL RUMBLE / {name === 'profile' ? fighter.name : name?.toUpperCase()}</span><h2 id="dialog-title">{name ? titles[name] : ''}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={20}/></button></header>
    {name === 'profile' && <FighterProfile fighter={fighter} onBack={() => { select(fighter.id); close(); }}/>} 
    {name === 'fighters' && <><p className="dialog-description">Eight personalities. Eight ways to start trouble. Pick a fighter to inspect their dossier.</p><div className="fighter-catalog">{state.fighters.map(f => <motion.button whileHover={{ y: -3 }} key={f.id} className="fighter-catalog-card" onClick={() => select(f.id)}><span className="catalog-portrait" style={{ background: `${f.color}13` }}><Avatar fighter={f} size={90}/><span className="catalog-class" style={{ color: f.color }}>{f.class}</span></span><strong>{f.name}</strong><small>{f.title}</small><span className="catalog-stats"><span><Swords size={12}/>{f.attack}</span><span><Shield size={12}/>{f.defense}</span><span className="lime">{f.odds.toFixed(2)}×</span></span><span className="catalog-link">Open dossier<ChevronRight size={13}/></span></motion.button>)}</div></>}
    {name === 'market' && <MarketView quotes={state.audience.market}/>}
    {name === 'leaderboard' && <GlobalLeaderboard engine={engine} revision={state.audience.revision}/>}
    {name === 'history' && <><div className="wallet-summary"><div><Coin/><span><span className="eyebrow">SIMULATED USD</span><strong>{money(state.save.balance)}</strong></span></div><span>Made for play.<br/>No real-world value.</span></div><div className="history-stats"><div><span>ROUNDS WATCHED</span><strong>{state.save.roundsWatched}</strong></div><div><span>PREDICTIONS WON</span><strong>{state.save.predictions.filter(p => p.status === 'won').length}</strong></div><div><span>TOTAL PAYOUTS</span><strong>{money(state.save.totalWon)}</strong></div></div><div className="dialog-tabs">{['predictions', 'transactions', 'achievements'].map(tab => <button className={historyTab === tab ? 'selected' : ''} key={tab} onClick={() => setHistoryTab(tab)}>{tab}</button>)}</div>
      {historyTab === 'predictions' && <div className="history-list">{state.save.predictions.length ? state.save.predictions.map(p => <div className="history-row" key={p.id}><span className={`prediction-result ${p.status}`}>{p.status === 'won' ? <Trophy size={17}/> : p.status === 'lost' ? <X size={17}/> : <Target size={17}/>}</span><div><strong>{p.fighterName} <span>· ROUND {String(p.round).padStart(3, '0')}</span></strong><small>{money(p.amount)} at {p.odds.toFixed(2)}× · {p.type}</small></div><span className={`history-status ${p.status}`}>{p.status === 'pending' ? 'IN PLAY' : p.status === 'won' ? `${signedMoney(p.payout - p.amount)} profit` : signedMoney(-p.amount)}</span></div>) : <Empty text="No predictions yet." detail="Back a fighter during the next open prediction window."/>}</div>}
      {historyTab === 'transactions' && <div className="history-list">{state.save.transactions.map(t => <div className="history-row" key={t.id}><Coin small/><div><strong>{t.label}</strong><small>{new Date(t.time).toLocaleString()}</small></div><span className={t.amount >= 0 ? 'positive' : 'negative'}>{signedMoney(t.amount)}</span></div>)}</div>}
      {historyTab === 'achievements' && <div className="achievements-grid">{[['Skin in the game', 'Make your first prediction'], ['Called it', 'Win a prediction'], ['Underdog believer', 'Win at 8× odds or higher'], ['Meet the underground', 'Inspect all eight fighters'], ['Arena regular', 'Watch 10 complete rounds']].map(([title, detail]) => <div className={`achievement ${state.save.achievements.includes(title) ? 'unlocked' : ''}`} key={title}><Trophy size={23}/><strong>{title}</strong><small>{detail}</small>{state.save.achievements.includes(title) && <Check size={13}/>}</div>)}</div>}
    </>}
    {name === 'settings' && <SettingsPanel settings={state.save.settings} engine={engine}/>}
    {name === 'help' && <><p className="help-intro">SMALL FIGHTERS.<br/><span>BIG CHAOS.</span></p><p className="dialog-description">You're the spectator. They're the trouble. Watch autonomous fighters clash, study their form, and put simulated dollars behind your instinct.</p><div className="help-steps">{[[Eye, '01', 'Read the room', 'Inspect fighters, watch their stats, and check the payout multipliers.'], [Target, '02', 'Make your call', 'During the 22-second window, select a fighter and commit $50.00–$5,000.00 simulated USD. One prediction per round.'], [Swords, '03', 'Let them rumble', 'Fighters move and attack automatically. Most eliminations wins; total damage breaks a tie. Death means a 5-second reconstruction.'], [Trophy, '04', 'Take your winnings', 'Winning returns your stake × locked odds. A losing wager returns zero. Everyone earns $150.00 in simulated dollars for watching a complete round.']].map(([Icon, number, title, description]) => { const Symbol = Icon as typeof Eye; return <div key={String(number)}><span><Symbol size={21}/></span><div><small>STEP {String(number)}</small><h3>{String(title)}</h3><p>{String(description)}</p></div></div>; })}</div><div className="help-fineprint"><Sparkles size={18}/><p>Every round brings a twist. Arenas rotate every two rounds. Boss invasions unite fighters for one life each: predict the winning side, top damage dealer, or longest survivor. Survival ties use remaining health. Double Rewards multiplies payouts; Underdog Bonus boosts odds of 8× or more.</p></div><div className="simulation-notice"><Shield size={16}/>All dollar balances, spectators, and market values are entirely fictional. No deposits, withdrawals, payments, wallets, or blockchain connections.</div></>}
    </div></dialog>;
}
function Empty({ text, detail }: { text: string; detail: string }) { return <div className="empty-state"><Target size={25}/><strong>{text}</strong><span>{detail}</span></div>; }
function FighterProfile({ fighter: f, onBack }: { fighter: Fighter; onBack: () => void }) {
  return <><div className="profile-hero" style={{ '--fighter-color': f.color } as React.CSSProperties}><Avatar fighter={f} size={116}/><div><span className="profile-class">{f.class} / {f.weapon}</span><h3>{f.name}<span>#{String(f.appearance + 1).padStart(3, '0')}</span></h3><p>{f.title}</p><span className="profile-status"><span className="live-dot"/>{f.health > 0 ? 'ALIVE AND DANGEROUS' : 'RECONSTRUCTING'}</span></div><div className="profile-odds"><span>BASE ODDS</span><strong>{f.odds.toFixed(2)}×</strong></div></div><div className="profile-health"><span><Heart size={12}/>HEALTH<b>{Math.ceil(f.health)} / {f.maxHealth}</b></span><div><i style={{ width: `${f.health / f.maxHealth * 100}%`, background: f.color }}/></div></div><div className="profile-stats">{[['Attack', f.attack, Swords], ['Defense', f.defense, Shield], ['Speed', f.speed, Zap], ['Crit chance', `${Math.round(f.critical * 100)}%`, Target], ['Dodge chance', `${Math.round(f.dodge * 100)}%`, Activity], ['Aggression', `${Math.round(f.aggression * 100)}%`, Skull]].map(([label, value, Icon]) => { const Symbol = Icon as typeof Swords; return <div key={String(label)}><Symbol size={16}/><span>{String(label)}</span><strong>{String(value)}</strong></div>; })}</div><div className="profile-record">{[['Wins', f.wins], ['Losses', f.losses], ['Kills', f.kills], ['Deaths', f.deaths], ['Streak', f.streak], ['Best streak', f.longestStreak]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="profile-lower"><div><span className="eyebrow">RECENT FORM</span><div className="recent-form">{f.recent.slice(-7).map((win, i) => <span key={i} className={win ? 'win' : 'loss'}>{win ? 'W' : 'L'}</span>)}</div><p>{Math.round(f.wins / (f.wins + f.losses) * 100)}% lifetime win rate</p></div><div><span className="eyebrow">${f.token} · FICTIONAL TOKEN</span><div className="profile-token"><strong>{money(f.price)}</strong><Sparkline values={f.priceHistory} width={100} color={f.color}/></div><p className={f.change >= 0 ? 'positive' : 'negative'}>{f.change >= 0 ? '+' : ''}{f.change.toFixed(2)}% this round</p></div></div><button className="primary-button" onClick={onBack}><Target size={16}/>BACK {f.name}</button><p className="fictional-note">The battle continues while you inspect.</p></>;
}
function SettingsPanel({ settings, engine }: { settings: Settings; engine: GameEngine }) {
  const toggles: { key: keyof Settings; title: string; detail: string }[] = [{ key: 'sound', title: 'Arcade audio', detail: 'Synthesized combat sounds and arena atmosphere.' }, { key: 'reducedMotion', title: 'Reduced motion', detail: 'Reduce flashes and decorative movement. Combat keeps running.' }, { key: 'shake', title: 'Screen shake', detail: 'A little impact when a fighter goes down.' }, { key: 'hazards', title: 'Environmental hazards', detail: 'Allow arena traps to affect the fighters.' }];
  return <div className="settings-list">{toggles.map(toggle => <label className="setting-row" key={toggle.key}><span><strong>{toggle.title}</strong><small>{toggle.detail}</small></span><input type="checkbox" role="switch" checked={Boolean(settings[toggle.key])} onChange={e => engine.setSettings({ [toggle.key]: e.target.checked })}/></label>)}<h3 className="settings-section"><Volume2 size={15}/>VOLUME & EFFECTS</h3>{([['master', 'Master volume'], ['music', 'Music'], ['effects', 'Sound effects'], ['particles', 'Particle intensity']] as const).map(([key, label]) => <label className="setting-slider" key={key}><span>{label}<b>{Math.round(settings[key] * 100)}%</b></span><input type="range" min="0" max="1" step="0.05" value={settings[key]} onChange={e => engine.setSettings({ [key]: Number(e.target.value) })}/></label>)}<p className="settings-note">Settings and simulated dollars are saved on this device. Audio starts only after you interact. Hidden tabs pause the simulation.</p></div>;
}
